### ISSUE TITLE
Blur is covering whole screen and giving me no time to see the question

### ISSUE THREAD

**Issue by sanjeevbishnoi** [frideosapps/trivia_example#1]
First of all, Thanks for this wonderful code.
See the bug in video.
[https://drive.google.com/file/d/1y7ZSjSxH-CQrXrplZWWqrvUVu1xDIQgw/view?usp=sharing](url)

it seems to countdown widget if I comment it it works well , If i go deeper even if I comment the blurwidget even then it works. 
but I am surprised why it is not working on my android 9.0 . 

thanks.

**Comment by frideosapps** [comment]
Hello @CodeNextGen, thank you for pointing it out. Unfortunately I can't replicate this weird behavior, in my emulator with android 9.0 it seems to work as expected. Are you building with the Flutter stable branch (1.2.1)?

**Comment by sanjeevbishnoi** [comment]
this is what I got from **flutter doctor -v**

[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.2 18C54, locale en-IN)
    • Flutter version 1.3.8 at /Users/sanjeevmoga/Documents/flutter/flutter
    • Framework revision e5b1ed7a7f (5 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

**Comment by sanjeevbishnoi** [comment]
On this thread I got the solution, will implement soon.
[https://github.com/flutter/flutter/issues/16614](url)

**Comment by frideosapps** [comment]
My advise is to switch to the stable version for now unless you don't need the beta for some particular reason. I've just read that issue and the related ones and I am a little bit confused so I'll wait for the next stable version before making any changes to the package. For now I'm going to close this issue.

**Comment by sanjeevbishnoi** [comment]
Thanks frideosapps,
Yes we must use stable version but if anybody is facing same problem the solution is wherever you are using BackdropFilter in the code , just make it child of ClipRect that it.

as Blur was part of your frideos package so rather then downgrading flutter or change your package code what I did was just 
 
[https://gist.github.com/CodeNextGen/27d8e9471d8031852fd9f86cb23bca39](url)
**(Just copy and paste in browser if it is redirecting on nothing )**
and everything worked with perfection. 

Thanks again for great code.

**Comment by frideosapps** [comment]
@CodeNextGen thanks for your gists. I've pinned this issue so other people facing the same problem can see and use your solution until the release of the fixed version of the package (I'll wait for the next stable version to be sure won't be other not expected behaviors). Thanks.

**Comment by frideosapps** [comment]
Package v0.6.2  updated with the fix.
